### ISSUE TITLE
KP115 not Showing

### ISSUE THREAD

**Issue by SteveSBE** [jimboca/udi-poly-kasa#20]
I am trying to get a KP115 to show in the ISY Admin console but all I see is the "Kasa Controller" which is the only node showing in Polisy.  I believe I followed the instructions correctly but it's been over an hour and the KP115 still doesn't show. 

Steve

**Comment by jimboca** [comment]
Others on the forum have mentioned that one is not working, it may be due to the newer firmware that disables our local access:  https://forum.universal-devices.com/search/?q=KP115

It is not listed as supported in the library used by this Nodeserver: https://github.com/python-kasa/python-kasa

You can PM me on the forum and send the file from Download Log Package and I can take a look, but probably nothing we can do except complain to TP-Link...

**Comment by jimboca** [comment]
Actually #19 was able to get it to show up, so it must be working, unless yours has a newer version of the firmware....

**Comment by SteveSBE** [comment]
It just showed up...I got to thinking it was a network issue so re-added my wired and wireless networks to Polisy.  It showed up just after that.  Thanks for looking into it so quickly. I'll close the issue...
